### ISSUE TITLE
Man does not use MAN_PAGE const from coreutils

### ISSUE THREAD

**Issue by rushsteve1** [redox-os/extrautils#12]
All coreutils have a `MAN_PAGE` `const` that acts as the help text. `man` completely ignores this and instead checks the `/ref/` directory, which does not always accurately reflect current version of the command, and often does not contain a manual page for the command at all.

**Comment by jackpot51** [comment]
You must `make refs`

**Comment by rushsteve1** [comment]
Oh my bad for not reading the full makefile. Never mind then.
